import re
import datetime
import httpx
from backend.config import NOVELAI_API_KEY, NOVELAI_BASE_URL

# Default fallback values in case generation fails
DEFAULT_FALLBACK_POSTS = [
    {
        "name": "Daine",
        "handle": "@notdaine",
        "content": "writing songs on the bedroom floor at 3am is a lifestyle. new demos coming."
    },
    {
        "name": "Alex",
        "handle": "@alextunes",
        "content": "just listened to the new track Daine posted. absolute bedroom pop gold."
    }
]

def get_world_context_from_db() -> str:
    try:
        from backend.database import SessionLocal, Setting
        db = SessionLocal()
        try:
            setting = db.query(Setting).filter_by(id=1).first()
            return setting.world_context.strip() if (setting and setting.world_context) else ""
        finally:
            db.close()
    except Exception as e:
        print(f"[Error getting world context]: {e}")
        return ""

async def generate_completion(prompt: str, max_tokens: int = 150, temperature: float = 0.8, stop: list = None) -> str:
    """
    Sends a completion request to the NovelAI OpenAI-compatible completions endpoint.
    """
    if not NOVELAI_API_KEY:
        # If API key is missing, log a warning and return mock/empty response to keep app running in offline dev mode
        print("[WARNING] NOVELAI_API_KEY is not set. Using empty string fallback.")
        return ""

    headers = {
        "Authorization": f"Bearer {NOVELAI_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "xialong-v1",
        "prompt": prompt,
        "max_tokens": max_tokens,
        "temperature": temperature,
        "top_p": 0.9,
    }
    if stop:
        payload["stop"] = stop

    url = f"{NOVELAI_BASE_URL}/completions"
    
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["text"]
    except httpx.HTTPStatusError as e:
        print(f"[Error] NovelAI API returned error status {e.response.status_code}: {e.response.text}")
        raise e
    except Exception as e:
        print(f"[Error] Failed to connect to NovelAI API: {e}")
        raise e

def parse_generated_posts(text: str) -> list:
    """
    Parses a batch of timeline posts generated by NovelAI.
    Standardizes '====' separators to '----' and discards redacted or malformed content.
    """
    # Replace alternative separators the AI might produce
    text = text.replace("====", "----")
    
    posts = []
    chunks = text.split("----")
    
    for chunk in chunks:
        lines = [line.strip() for line in chunk.split("\n") if line.strip()]
        if not lines:
            continue
            
        # Ignore chunks containing redactions or bracketed placeholders
        placeholder_pat = r'\[(?:reply|response|insert|write|text|content|comment|here).*?\]'
        if any("[REDACTED]" in line for line in lines) or any(re.search(placeholder_pat, line, re.IGNORECASE) for line in lines):
            continue
            
        # We search for the handle (starts with or contains '@')
        handle_idx = -1
        for i, line in enumerate(lines):
            if "@" in line:
                handle_idx = i
                break
        
        if handle_idx == -1:
            continue
            
        handle_line = lines[handle_idx]
        name = "Unknown"
        handle = "Unknown"
        
        # Check if handle line contains the name too (e.g. "daine @notdaine")
        if handle_line.strip().startswith("@"):
            if handle_idx > 0:
                name = lines[handle_idx - 1]
            handle = handle_line
        else:
            # Split on the @ symbol
            parts = handle_line.split("@", 1)
            name = parts[0].strip()
            handle = "@" + parts[1].strip()
            
        # Strip repost headers if any
        if "reposted:" in name.lower():
            name = name.split("reposted:")[0].strip()
            if not name and handle_idx > 1:
                name = lines[handle_idx - 2]

        if name == "Unknown" or "[REDACTED]" in name or not name:
            continue

        # Clean up handle: must start with @ and have only valid chars
        handle_match = re.search(r"@\w+", handle)
        if handle_match:
            handle = handle_match.group(0)
        else:
            continue # Ignore malformed handle records
            
        if "[REDACTED]" in handle:
            continue

        content_start_idx = handle_idx + 1
        if content_start_idx < len(lines) and (
            lines[content_start_idx].startswith("*") or 
            "XM" in lines[content_start_idx] or 
            "AM" in lines[content_start_idx] or 
            "PM" in lines[content_start_idx]
        ):
            content_start_idx += 1
            
        content_lines = lines[content_start_idx:]
        if not content_lines:
            continue
            
        content = "\n".join(content_lines)
        if not content.strip() or "[REDACTED]" in content:
            continue
            
        posts.append({
            "name": name,
            "handle": handle,
            "content": content
        })
        
    return posts

def parse_dm_response(text: str) -> dict:
    """
    Parses a DM response which is expected to follow the format:
    Vibe: [Vibe description]
    Intensity: [Vibe intensity %]
    Message: [The message text]
    
    Returns a dict: {"vibe": str, "intensity": int, "text": str}
    """
    vibe = "Neutral"
    intensity = 50
    message = text.strip()

    # Try matching lines
    vibe_match = re.search(r"Vibe:\s*(.*)", text, re.IGNORECASE)
    intensity_match = re.search(r"Intensity:\s*(\d+)", text, re.IGNORECASE)
    message_match = re.search(r"Message:\s*([\s\S]*)", text, re.IGNORECASE)

    if vibe_match:
        vibe = vibe_match.group(1).strip()
    if intensity_match:
        try:
            intensity = int(intensity_match.group(1).strip())
            # bound check
            intensity = max(0, min(100, intensity))
        except ValueError:
            pass
    if message_match:
        message = message_match.group(1).strip()
    else:
        # If Message: tag wasn't found but we got other tags, clean up the text
        # by removing Vibe: and Intensity: lines
        cleaned = []
        for line in text.split("\n"):
            if not (line.lower().startswith("vibe:") or line.lower().startswith("intensity:") or line.lower().startswith("message:")):
                cleaned.append(line)
        message = "\n".join(cleaned).strip()

    return {
        "vibe": vibe,
        "intensity": intensity,
        "text": message
    }

def format_tweet_history(name: str, handle: str, tweet_history: str) -> str:
    """
    Formats a raw tweet history string (one tweet per line) into the standard structured format:
    Name @handle
    * 00:00 AM
    Tweet content
    ----
    """
    if not tweet_history:
        return ""
    
    # Split by newlines and clean
    lines = [line.strip() for line in tweet_history.split("\n") if line.strip()]
    formatted_posts = []
    
    # Generate some slightly varied times to make it look realistic
    hours = [3, 8, 11, 2, 6, 10]
    minutes = [15, 30, 45, 12, 20, 55]
    meridians = ["AM", "PM", "AM", "PM", "AM", "PM"]
    
    for idx, content in enumerate(lines):
        # Skip separator lines or headers if they got in there
        if content == "----" or content == "====" or content.startswith("*@"):
            continue
            
        h = hours[idx % len(hours)]
        m = minutes[idx % len(minutes)]
        mer = meridians[idx % len(meridians)]
        time_str = f"{h:02d}:{m:02d} {mer}"
        
        # Format name and handle on the same line
        formatted_posts.append(f"{name} {handle}\n* {time_str}\n{content}\n----")
        
    return "\n".join(formatted_posts) + "\n"

async def generate_timeline_posts(community_name: str, seed_history: str = "") -> list:
    """
    Generates new posts for a specific community. Incorporates world context.
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    # Fetch active characters to construct instruction prompt
    active_handles = []
    try:
        from backend.database import SessionLocal, Character
        db = SessionLocal()
        try:
            chars = db.query(Character).filter(Character.is_user == False, Character.handle != "@popcraze").all()
            active_handles = [c.handle for c in chars]
        finally:
            db.close()
    except Exception:
        pass

    if active_handles:
        handles_str = ", ".join(active_handles)
        instruction = (
            f"{{Generate a batch of short, realistic, single-perspective Twitter/X timeline posts about the {community_name} scene. "
            f"Do not write dialogue scripts, play scripts, or conversations between multiple users. "
            f"Write posts for some of the following active users: {handles_str}. "
            f"Each post must follow the exact format of the examples below, separated by '----'.}}"
        )
    else:
        instruction = (
            f"{{Generate a batch of short, realistic, single-perspective Twitter/X timeline posts about the {community_name} scene. "
            f"Do not write dialogue scripts, play scripts, or conversations between multiple users. "
            f"Each post must follow the exact format of the examples below, separated by '----'.}}"
        )
    
    prompt = f"{wc_prefix}{instruction}\n"
    
    # Format and shuffle seed history to guide the model cleanly
    seed_posts = []
    if seed_history:
        # Standardize separators and split
        normalized = seed_history.replace("====", "----")
        raw_chunks = normalized.split("----")
        for chunk in raw_chunks:
            cleaned_chunk = chunk.strip()
            if cleaned_chunk:
                seed_posts.append(cleaned_chunk)
                
    if seed_posts:
        import random
        random.shuffle(seed_posts)
        # Select up to 5 posts to keep prompt compact and fast
        selected_seeds = seed_posts[:5]
        prompt += "\n----\n".join(selected_seeds) + "\n----\n"
    else:
        # Default seed format to guide the model if seed history is missing
        prompt += (
            "daine @notdaine\n* 03:15 AM\nwriting songs on the bedroom floor at 3am is a lifestyle. new demos soon.\n----\n"
            "Ella @moviesforguyss\n* 03:15 PM\nSobbing my eyes out listening to don't mind me by Quadeca. hits way too hard today.\n----\n"
        )
    
    try:
        raw_output = await generate_completion(prompt, max_tokens=300, temperature=0.85)
        if not raw_output:
            return DEFAULT_FALLBACK_POSTS
        parsed = parse_generated_posts(raw_output)
        return parsed
    except Exception:
        return DEFAULT_FALLBACK_POSTS

async def generate_dm_reply(char_name: str, char_handle: str, char_bio: str, char_avatar_alt: str, tweet_history: str, message_history: list) -> dict:
    """
    Generates a DM reply using the custom Vibe/Intensity format, incorporating world context.
    message_history is a list of dicts: [{'sender': str, 'content': str}]
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    # Fetch social relationship context
    social_context = ""
    target_rel_context = ""
    try:
        from backend.database import SessionLocal, Character
        from backend.crud import get_character_social_context
        db = SessionLocal()
        try:
            char = db.query(Character).filter_by(handle=char_handle).first()
            if char:
                social_context = get_character_social_context(db, char.id)
                if char.target_relationship:
                    target_rel_context = f"[ Relationship Stance: {char_name} is the user's {char.target_relationship} ]\n"
        finally:
            db.close()
    except Exception:
        pass
    sc_prefix = f"{social_context}\n" if social_context else ""
    tr_prefix = f"{target_rel_context}" if target_rel_context else ""
    
    history_str = ""
    for msg in message_history:
        history_str += f"{msg['sender']}: {msg['content']}\n"
        
    alt_text_str = f"[Character Appearance Description: {char_avatar_alt}]\n" if char_avatar_alt else ""
    
    instruction = f"{{Generate the next direct message reply in the following chat. Write your reply as a structured block detailing the character's internal vibe, the intensity of that vibe, and the chat response.}}"
    
    prompt = (
        f"{wc_prefix}"
        f"{sc_prefix}"
        f"{tr_prefix}"
        f"{instruction}\n"
        f"Character: {char_name} ({char_handle})\n"
        f"Bio: {char_bio}\n"
        f"{alt_text_str}"
        f"\n{char_name}'s Post Style Examples:\n"
        f"{tweet_history}\n"
        f"Message History:\n"
        f"{history_str}"
        f"\nResponse Format:\n"
        f"Vibe: [Describe the character's emotional subtext, e.g., \"flustered yet amused\"]\n"
        f"Intensity: [An integer from 0 to 100 representing intensity]\n"
        f"Message: [The message text]\n\n"
        f"Response:\n"
        f"Vibe:"
    )
    
    try:
        raw_output = await generate_completion(prompt, max_tokens=150, temperature=0.75, stop=[f"\n{char_name}", "\nMessage History:"])
        # Since we prefilled "Vibe:", prepend it back to raw_output to parse correctly
        full_text = "Vibe:" + raw_output
        return parse_dm_response(full_text)
    except Exception:
        # Safe fallback
        return {
            "vibe": "Slightly flustered",
            "intensity": 60,
            "text": "Uh, sorry, my signal cut out for a second. What were we saying?"
        }

async def generate_thread_reply(
    char_name: str, 
    char_handle: str, 
    char_bio: str, 
    tweet_history: str, 
    thread_history: list,
    replying_to_user: bool = False,
    user_handle: str = "@playerone"
) -> str:
    """
    Generates a single character's reply to an existing timeline thread, incorporating world context.
    thread_history is a list of dicts: [{'handle': str, 'content': str}]
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    # Fetch social relationship context
    social_context = ""
    target_rel_context = ""
    try:
        from backend.database import SessionLocal, Character
        from backend.crud import get_character_social_context
        db = SessionLocal()
        try:
            char = db.query(Character).filter_by(handle=char_handle).first()
            if char:
                social_context = get_character_social_context(db, char.id)
                if char.target_relationship:
                    target_rel_context = f"[ Relationship Stance: {char_name} is the user's {char.target_relationship} ]\n"
        finally:
            db.close()
    except Exception:
        pass
    sc_prefix = f"{social_context}\n" if social_context else ""
    tr_prefix = f"{target_rel_context}" if target_rel_context else ""
    
    history_str = ""
    for post in thread_history:
        history_str += f"{post['handle']}: {post['content']}\n"
        
    if replying_to_user:
        instruction = f"{{Below is an online social media thread. Write a reply from {char_name} ({char_handle}) directly replying to the user ({user_handle}). Start your reply by mentioning {user_handle}. Keep it short, conversational, and in character.}}"
        prefill = f"{char_handle}: {user_handle}"
    else:
        instruction = f"{{Below is an online social media thread. Write a reply from {char_name} ({char_handle}) reacting to the conversation. Keep it short, conversational, and in character.}}"
        prefill = f"{char_handle}:"
    
    prompt = (
        f"{wc_prefix}"
        f"{sc_prefix}"
        f"{tr_prefix}"
        f"{instruction}\n"
        f"Character: {char_name} ({char_handle})\n"
        f"Bio: {char_bio}\n"
        f"\n{char_name}'s Post Style Examples:\n"
        f"{tweet_history}\n"
        f"Thread:\n"
        f"{history_str}"
        f"{prefill}"
    )
    
    try:
        raw_output = await generate_completion(prompt, max_tokens=80, temperature=0.8, stop=["\n@", "\n----"])
        reply = raw_output.strip()
        
        # Check for bracketed placeholders like [reply here] or [insert response]
        placeholder_pat = r'\[(?:reply|response|insert|write|text|content|comment|here).*?\]'
        if re.search(placeholder_pat, reply, re.IGNORECASE) or not reply:
            # Fallback attempt with a lower temperature
            raw_output = await generate_completion(prompt, max_tokens=80, temperature=0.5, stop=["\n@", "\n----"])
            reply = raw_output.strip()
            
            if re.search(placeholder_pat, reply, re.IGNORECASE) or not reply:
                # Character-specific defaults to maintain immersion
                defaults = {
                    "@notdaine": "hahaha true",
                    "@darcyebaylis": "yeah honestly",
                    "@carolinecalloway": "omg details please",
                    "@avgcowgirl": "real",
                    "@ninajirachi": "lmao wait what",
                    "@quannnic": "so true",
                    "@photographicmemory": "damn"
                }
                reply = defaults.get(char_handle, "yeah")
                
        if replying_to_user:
            # Check if the generated output already starts with or includes the handle to avoid repetition
            if not reply.startswith(user_handle) and not reply.startswith("@"):
                reply = f"{user_handle} {reply}"
        return reply
    except Exception:
        if replying_to_user:
            return f"{user_handle} wait, really?"
        return "wait, really?"

async def generate_gossip_headline(char_a_name: str, char_b_name: str, recent_event_summary: str = "") -> str:
    """
    Generates a dramatic pop-culture gossip headline about two characters, incorporating world context.
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    # Look up if there is a recorded relationship between Person A and Person B
    relationship_context = ""
    try:
        from backend.database import SessionLocal, Character, CharacterRelationship
        db = SessionLocal()
        try:
            char_a = db.query(Character).filter(Character.name.like(f"%{char_a_name}%")).first()
            char_b = db.query(Character).filter(Character.name.like(f"%{char_b_name}%")).first()
            if char_a and char_b:
                rel = db.query(CharacterRelationship).filter(
                    ((CharacterRelationship.character_a_id == char_a.id) & (CharacterRelationship.character_b_id == char_b.id)) |
                    ((CharacterRelationship.character_a_id == char_b.id) & (CharacterRelationship.character_b_id == char_a.id))
                ).first()
                if rel:
                    relationship_context = f"[ Relationship Context: {char_a_name} and {char_b_name} are: {rel.relationship_type}s ]\n"
        finally:
            db.close()
    except Exception:
        pass
    
    instruction = "{Generate a dramatic pop-culture gossip headline about the recent interactions between the two mentioned people. Keep it scandalous and under 25 words. Do not use quotes.}"
    
    prompt = (
        f"{wc_prefix}"
        f"{relationship_context}"
        f"{instruction}\n"
        f"Person A: {char_a_name}\n"
        f"Person B: {char_b_name}\n"
    )
    if recent_event_summary:
        prompt += f"Context: {recent_event_summary}\n"
    prompt += "Headline:"
    
    try:
        raw_output = await generate_completion(prompt, max_tokens=40, temperature=0.85, stop=["\n"])
        return raw_output.strip()
    except Exception:
        return f"EXCLUSIVE: Rumors swirling about {char_a_name} and {char_b_name} after a mysterious studio sighting last night!"

async def generate_narrative_outcome(context_desc: str, user_reply: str) -> str:
    """
    Generates a single dramatic sentence outcome of the user's latest interaction.
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    instruction = "{Generate a single, stylish, and dramatic sentence describing the narrative outcome of the user's latest message in this conversation. Write ONLY the sentence. Do not add quotes.}"
    
    prompt = (
        f"{wc_prefix}"
        f"{instruction}\n"
        f"Context: {context_desc}\n"
        f"User Reply: {user_reply}\n"
        f"Outcome:"
    )
    try:
        raw_output = await generate_completion(prompt, max_tokens=50, temperature=0.8, stop=["\n"])
        return raw_output.strip().replace('"', '')
    except Exception:
        return "The digital air shifted slightly as the community took note of the player's response."

async def generate_social_event(characters_info: list) -> str:
    """
    Generates a social dilemma event scenario involving 1-3 characters.
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    char_details = ""
    char_names = []
    for char in characters_info:
        char_details += f"Character: {char['name']} ({char['handle']})\nBio: {char['bio']}\n"
        char_names.append(char['name'])
        
    names_str = " and ".join(char_names)
    instruction = f"{{Generate a short, dramatic scenario involving You (the user) and {names_str} that requires the user to make a difficult social choice. End the scenario with a direct question asking the user what they will do.}}"
    
    prompt = (
        f"{wc_prefix}"
        f"{instruction}\n"
        f"{char_details}\n"
        f"Event:"
    )
    try:
        raw_output = await generate_completion(prompt, max_tokens=180, temperature=0.85)
        return raw_output.strip()
    except Exception:
        return f"A rumor starts circulating that Soren and Pop Craze are collaborating secretly. You notice them whispering in the green room. What will you do?"

async def generate_event_resolution(scenario_text: str, user_action: str) -> str:
    """
    Based on user's action, describes the outcome in a stylish paragraph.
    Concludes with relationship impact.
    """
    world_context = get_world_context_from_db()
    wc_prefix = f"[ World Context: {world_context} ]\n" if world_context else ""
    
    instruction = "{Based on the user's chosen action, describe the outcome of this scenario in a stylish, narrative paragraph. Conclude by explicitly stating if this positively or negatively affected their relationship with the characters.}"
    
    prompt = (
        f"{wc_prefix}"
        f"{instruction}\n"
        f"Scenario: {scenario_text}\n"
        f"User Action: {user_action}\n"
        f"Resolution:"
    )
    try:
        raw_output = await generate_completion(prompt, max_tokens=150, temperature=0.8)
        return raw_output.strip()
    except Exception:
        return "Your action resolved the crisis. It positively affected your relationship with Soren, but negatively affected your reputation with Pop Craze."

